import type { Metadata } from "next";
import { Inter } from "next/font/google";

const interFont = Inter({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
    variable: "--font-inter",
});

import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} antialiased`}
      >
           <Navbar />
        {children}
        <footer className="bg-gray-800 text-white py-4 text-center">
        © 2023 Tile Agency. All rights reserved.
      </footer>
      </body>
    </html>
  );
}