import type { Metadata } from "next";
import { Inter } from "next/font/google";

const interFont = Inter({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
    variable: "--font-inter",
});

import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${interFont.variable} antialiased`}
      >
           <Navbar />
        {children}
        <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <h3 className="text-xl font-bold mb-4">Earth Elements</h3>
              <p>Your premier destination for luxury and modern interior design.</p>
            </div>
            {['Our Services', 'Our Projects', 'Resources'].map((title) => (
              <div key={title}>
                <h3 className="text-xl font-bold mb-4">{title}</h3>
                <ul className="space-y-2">
                  <li>
                    <a href="#" className="hover:underline">
                      Link 1
                    </a>
                  </li>
                  <li>
                    <a href="#" className="hover:underline">
                      Link 2
                    </a>
                  </li>
                  <li>
                    <a href="#" className="hover:underline">
                      Link 3
                    </a>
                  </li>
                  <li>
                    <a href="#" className="hover:underline">
                      Link 4
                    </a>
                  </li>
                </ul>
              </div>
            ))}
          </div>
          <div className="mt-8 pt-8 border-t border-gray-800 text-center">
            <p>&copy; 2023 Earth Elements. All rights reserved.</p>
          </div>
        </div>
      </footer>
      </body>
    </html>
  );
}